import "./globals.css";
import NativeProvider from "@/components/native-provider";
import CookieConsent from "@/components/cookie-consent";

export const metadata = {
  metadataBase: new URL("https://www.swaptest.co.uk"),
  title: "Swap Driving Test Date With Someone | SwapTest UK",
  description: "Swap a driving test for an earlier date. SwapTest is the free UK service to swap a DVSA driving test with someone who wants your date. Match in minutes at your centre or nearby.",
  keywords: [
    "swap driving test",
    "dvsa swap driving test with someone",
    "how to swap driving test date with someone",
    "dvsa swap driving test",
    "swap driving test uk",
    "swap driving test date",
  ],
  authors: [{ name: "SwapTest" }],
  category: "Driving",
  applicationName: "SwapTest",
  openGraph: {
    title: "Swap Driving Test Date With Someone | SwapTest UK",
    description: "The free UK service to swap a DVSA driving test date with someone who wants yours. Match at your test centre or a nearby one in minutes.",
    url: "https://www.swaptest.co.uk",
    siteName: "SwapTest",
    type: "website",
    locale: "en_GB",
    // og:image is generated by app/opengraph-image.js
  },
  twitter: {
    card: "summary_large_image",
    title: "Swap Driving Test Date With Someone | SwapTest UK",
    description: "Free UK service to swap a DVSA driving test date with someone who wants yours. Match at your centre or nearby.",
    // twitter:image is generated by app/twitter-image.js
  },
  robots: {
    index: true,
    follow: true,
    googleBot: { index: true, follow: true, "max-image-preview": "large", "max-snippet": -1 },
  },
  alternates: {
    canonical: "https://www.swaptest.co.uk",
  },
};

export const viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 5,
  viewportFit: "cover",
};

// Structured data for Google: FAQ rich results + site identity
const jsonLd = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "WebSite",
      "@id": "https://www.swaptest.co.uk/#website",
      url: "https://www.swaptest.co.uk",
      name: "SwapTest",
      description: "Free UK driving test date swapping and matching service",
      potentialAction: {
        "@type": "SearchAction",
        target: "https://www.swaptest.co.uk/register",
        "query-input": "required name=search_term_string",
      },
    },
    {
      "@type": "Organization",
      "@id": "https://www.swaptest.co.uk/#organization",
      name: "SwapTest",
      url: "https://www.swaptest.co.uk",
      description: "Free UK driving test date swapping and matching service. Connects DVSA test candidates who want to swap dates at the same or nearby test centres.",
    },
    {
      "@type": "FAQPage",
      "@id": "https://www.swaptest.co.uk/#faq",
      mainEntity: [
        {
          "@type": "Question",
          name: "How to swap driving test date with someone?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "To swap a driving test date with someone, list your current DVSA test date and the dates you would prefer on SwapTest. We match you with another learner who wants your date and is holding a date that suits you. Once you both agree, you exchange contact details and contact DVSA to arrange the swap. It is the simplest way to swap a driving test date with someone at the same or a nearby test centre.",
          },
        },
        {
          "@type": "Question",
          name: "How do you swap a driving test date?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "You swap a driving test date in four steps. First, add your test centre, current date and preferred dates. Second, SwapTest searches your centre and three nearby centres for a matching candidate. Third, both people agree to the swap. Fourth, you contact DVSA to arrange swapping your dates. You do not need to cancel your test first.",
          },
        },
        {
          "@type": "Question",
          name: "Can you swap driving test dates with someone?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Yes. You can swap driving test dates with someone who wants your slot and holds a date that suits you. Both candidates must agree, and you then contact DVSA to arrange the change. SwapTest makes it easy to find that person, so you can swap a driving test in the UK without waiting months for a new date.",
          },
        },
        {
          "@type": "Question",
          name: "How many times can you swap a driving test?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "There is no SwapTest limit on how many times you can look for a swap. You can list, match and swap as often as you need until you find a date that works. DVSA has its own rules on rescheduling a practical driving test, so always check the current guidance on GOV.UK before arranging another swap.",
          },
        },
        {
          "@type": "Question",
          name: "Can I swap to a different test centre?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Yes. DVSA allows you to move your test to one of 3 nearby centres. SwapTest automatically checks all nearby centres when finding matches. Both people must be able to move to each other's centre for a swap to be valid.",
          },
        },
        {
          "@type": "Question",
          name: "Is SwapTest really free?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Yes, completely free. No platform fees, no subscription, no hidden charges. We may introduce a small optional fee in the future, but the core matching service will remain free.",
          },
        },
        {
          "@type": "Question",
          name: "Is my personal information safe?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Your password is encrypted using bcrypt hashing and can never be seen by anyone, including us. Your contact details (email and phone) are only shared with your swap partner after both of you agree to swap. We never sell or share your data with third parties.",
          },
        },
        {
          "@type": "Question",
          name: "What happens if the other person doesn't respond?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "When you select a match, the other person has 30 minutes to agree. If they don't respond, the match expires automatically and your listing goes back into the pool. No harm done.",
          },
        },
        {
          "@type": "Question",
          name: "Can I cancel or edit my listing?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Yes. You can edit or delete your listing at any time from your dashboard, as long as it doesn't have an active match pending.",
          },
        },
      ],
    },
  ],
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700;800&display=swap"
          rel="stylesheet"
        />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
        <meta name="theme-color" media="(prefers-color-scheme: light)" content="#ffffff" />
        <meta name="theme-color" media="(prefers-color-scheme: dark)" content="#111110" />
        {/* Canonical, OG and Twitter tags are generated from the metadata export above. */}
        {/* No-flash theme init: applies stored choice, else OS preference, before paint.
            Default for a brand-new visitor with no signal is light (no .dark class). */}
        <script
          dangerouslySetInnerHTML={{
            __html:
              "(function(){try{var c=localStorage.getItem('swaptest-theme');var d=c?c==='dark':window.matchMedia('(prefers-color-scheme: dark)').matches;if(d)document.documentElement.classList.add('dark');}catch(e){}})();",
          }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
      </head>
      <body>
        <NativeProvider>{children}</NativeProvider>
        <CookieConsent />
      </body>
    </html>
  );
}
