// ============================================================
// lib/centres.js — DVSA Test Centres & Nearby Centres Map
// ============================================================
// Source: https://www.gov.uk/government/publications/check-which-driving-test-centres-you-can-move-your-test-to
// Each centre maps to its 3 nearest centres by driving distance.
// Updated: March 2026
// ============================================================

export const NEARBY_CENTRES = {
  // ── East of England ──
  "Basildon": ["Brentwood (London)", "Tilbury", "Southend-on-Sea"],
  "Bedford": ["Wellingborough", "Bletchley", "Letchworth"],
  "Bishops Stortford": ["Loughton (London)", "Chelmsford (Hanbury Road)", "Enfield (Innova Business Park)"],
  "Bletchley": ["Leighton Buzzard (Stanbridge Road)", "Aylesbury", "Luton"],
  "Bury St Edmunds": ["Cambridge (Brookmount Court)", "Ipswich", "Colchester"],
  "Cambridge (Brookmount Court)": ["Letchworth", "Bury St Edmunds", "Bishops Stortford"],
  "Chelmsford (Hanbury Road)": ["Brentwood (London)", "Basildon", "Hornchurch (London)"],
  "Clacton-on-Sea": ["Colchester", "Ipswich", "Chelmsford (Hanbury Road)"],
  "Colchester": ["Clacton-on-Sea", "Ipswich", "Chelmsford (Hanbury Road)"],
  "Ipswich": ["Colchester", "Clacton-on-Sea", "Bury St Edmunds"],
  "Kings Lynn": ["Boston", "Peterborough", "Bury St Edmunds"],
  "Letchworth": ["Stevenage", "Luton", "St Albans"],
  "Lowestoft (Mobbs Way)": ["Norwich (Peachman Way)", "Ipswich", "Bury St Edmunds"],
  "Luton": ["St Albans", "Leighton Buzzard (Stanbridge Road)", "Stevenage"],
  "Norwich (Peachman Way)": ["Lowestoft (Mobbs Way)", "Bury St Edmunds", "Kings Lynn"],
  "Peterborough": ["Kettering", "Boston", "Grantham (Somerby)"],
  "Southend-on-Sea": ["Basildon", "Chelmsford (Hanbury Road)", "Tilbury"],
  "St Albans": ["Watford", "Borehamwood (London)", "Barnet (London)"],
  "Stevenage": ["Letchworth", "Luton", "St Albans"],
  "Tilbury": ["Basildon", "Hornchurch (London)", "Brentwood (London)"],
  "Watford": ["Borehamwood (London)", "Pinner (London)", "Mill Hill (London)"],

  // ── East Midlands ──
  "Ashfield": ["Chesterfield", "Nottingham (Colwick)", "Worksop"],
  "Boston": ["Skegness", "Grantham (Somerby)", "Peterborough"],
  "Chesterfield": ["Sheffield (Handsworth)", "Ashfield", "Sheffield (Middlewood Road)"],
  "Derby (Alvaston)": ["Nottingham (Chilwell)", "Burton on Trent", "Loughborough"],
  "Grantham (Somerby)": ["Melton Mowbray", "Lincoln", "Nottingham (Colwick)"],
  "Grimsby Coldwater": ["Louth", "Scunthorpe", "Hull"],
  "Hinckley": ["Nuneaton", "Coventry", "Leicester (Wigston)"],
  "Kettering": ["Wellingborough", "Northampton", "Bedford"],
  "Leicester (Cannock Street)": ["Leicester (Wigston)", "Loughborough", "Melton Mowbray"],
  "Leicester (Wigston)": ["Leicester (Cannock Street)", "Hinckley", "Loughborough"],
  "Lincoln": ["Grantham (Somerby)", "Worksop", "Nottingham (Colwick)"],
  "Loughborough": ["Leicester (Cannock Street)", "Nottingham (Chilwell)", "Melton Mowbray"],
  "Louth": ["Grimsby Coldwater", "Skegness", "Lincoln"],
  "Melton Mowbray": ["Leicester (Cannock Street)", "Loughborough", "Grantham (Somerby)"],
  "Northampton": ["Wellingborough", "Kettering", "Rugby"],
  "Nottingham (Chilwell)": ["Nottingham (Colwick)", "Derby (Alvaston)", "Loughborough"],
  "Nottingham (Colwick)": ["Nottingham (Chilwell)", "Ashfield", "Loughborough"],
  "Skegness": ["Boston", "Louth", "Grimsby Coldwater"],
  "Wellingborough": ["Kettering", "Northampton", "Bedford"],
  "Worksop": ["Sheffield (Handsworth)", "Rotherham", "Chesterfield"],

  // ── London ──
  "Barking (Tanner Street)": ["Goodmayes (London)", "Wanstead (London)", "Hornchurch (London)"],
  "Barnet (London)": ["Borehamwood (London)", "Mill Hill (London)", "Wood Green (London)"],
  "Belvedere (London)": ["Erith (London)", "Sidcup (London)", "Barking (Tanner Street)"],
  "Borehamwood (London)": ["Mill Hill (London)", "Barnet (London)", "Hendon (London)"],
  "Brentwood (London)": ["Hornchurch (London)", "Goodmayes (London)", "Basildon"],
  "Bromley (London)": ["West Wickham (London)", "Sidcup (London)", "Mitcham (London)"],
  "Chertsey (London)": ["Guildford", "Slough (London)", "Tolworth (London)"],
  "Chingford (London)": ["Loughton (London)", "Enfield (Brancroft Way)", "Wanstead (London)"],
  "Enfield (Brancroft Way)": ["Enfield (Innova Business Park)", "Chingford (London)", "Tottenham"],
  "Enfield (Innova Business Park)": ["Enfield (Brancroft Way)", "Chingford (London)", "Tottenham"],
  "Erith (London)": ["Belvedere (London)", "Sidcup (London)", "Barking (Tanner Street)"],
  "Goodmayes (London)": ["Barking (Tanner Street)", "Wanstead (London)", "Hornchurch (London)"],
  "Greenford (Horsenden Lane)": ["Southall (London)", "Yeading (London)", "Pinner (London)"],
  "Hendon (London)": ["Mill Hill (London)", "Borehamwood (London)", "Barnet (London)"],
  "Hornchurch (London)": ["Goodmayes (London)", "Brentwood (London)", "Barking (Tanner Street)"],
  "Isleworth (Fleming Way)": ["Southall (London)", "Yeading (London)", "Tolworth (London)"],
  "Loughton (London)": ["Chingford (London)", "Wanstead (London)", "Enfield (Brancroft Way)"],
  "Mill Hill (London)": ["Hendon (London)", "Borehamwood (London)", "Barnet (London)"],
  "Mitcham (London)": ["Sidcup (London)", "Bromley (London)", "West Wickham (London)"],
  "Morden (London)": ["Tolworth (London)", "Isleworth (Fleming Way)", "West Wickham (London)"],
  "Pinner (London)": ["Greenford (Horsenden Lane)", "Yeading (London)", "Uxbridge (London)"],
  "Sidcup (London)": ["Mitcham (London)", "Belvedere (London)", "Bromley (London)"],
  "Slough (London)": ["Uxbridge (London)", "Yeading (London)", "Southall (London)"],
  "Southall (London)": ["Yeading (London)", "Greenford (Horsenden Lane)", "Isleworth (Fleming Way)"],
  "Tolworth (London)": ["Morden (London)", "Isleworth (Fleming Way)", "Chertsey (London)"],
  "Tottenham": ["Wood Green (London)", "Enfield (Brancroft Way)", "Chingford (London)"],
  "Uxbridge (London)": ["Yeading (London)", "Slough (London)", "Pinner (London)"],
  "Wanstead (London)": ["Barking (Tanner Street)", "Chingford (London)", "Goodmayes (London)"],
  "West Wickham (London)": ["Bromley (London)", "Mitcham (London)", "Sidcup (London)"],
  "Wood Green (London)": ["Tottenham", "Barnet (London)", "Hendon (London)"],
  "Yeading (London)": ["Southall (London)", "Greenford (Horsenden Lane)", "Uxbridge (London)"],

  // ── North-east England ──
  "Alnwick": ["Blyth", "Berwick-On-Tweed", "Gosforth"],
  "Berwick-On-Tweed": ["Duns", "Kelso", "Alnwick"],
  "Blyth": ["Gosforth", "Gateshead", "Sunderland"],
  "Darlington": ["Middlesbrough", "Northallerton", "Durham"],
  "Durham": ["Sunderland", "Gateshead", "Darlington"],
  "Gateshead": ["Gosforth", "Sunderland", "Blyth"],
  "Gosforth": ["Gateshead", "Blyth", "Sunderland"],
  "Hartlepool": ["Middlesbrough", "Darlington", "Durham"],
  "Hexham": ["Gateshead", "Gosforth", "Durham"],
  "Middlesbrough": ["Hartlepool", "Darlington", "Northallerton"],
  "Northallerton": ["Darlington", "Middlesbrough", "Knaresborough"],
  "Sunderland": ["Gateshead", "Gosforth", "Durham"],

  // ── North-west England ──
  "Atherton (Manchester)": ["Bolton (Manchester)", "Warrington", "Chorley"],
  "Barrow In Furness": ["Kendal (Oxenholme Road)", "Heysham", "Workington"],
  "Blackburn with Darwen": ["Chorley", "Bolton (Manchester)", "Preston"],
  "Blackpool": ["Preston", "Chorley", "Heysham"],
  "Bolton (Manchester)": ["Atherton (Manchester)", "Bury (Manchester)", "Cheetham Hill (Manchester)"],
  "Bredbury (Manchester)": ["West Didsbury (Manchester)", "Cheetham Hill (Manchester)", "Chadderton"],
  "Bury (Manchester)": ["Bolton (Manchester)", "Rochdale (Manchester)", "Chadderton"],
  "Buxton": ["Macclesfield", "Bredbury (Manchester)", "West Didsbury (Manchester)"],
  "Carlisle": ["Carlisle LGV (Cars)", "Dumfries", "Workington"],
  "Carlisle LGV (Cars)": ["Carlisle", "Dumfries", "Workington"],
  "Chadderton": ["Cheetham Hill (Manchester)", "Rochdale (Manchester)", "Bury (Manchester)"],
  "Cheetham Hill (Manchester)": ["Chadderton", "West Didsbury (Manchester)", "Sale (Manchester)"],
  "Chester": ["Wrexham", "Northwich", "Upton"],
  "Chorley": ["Blackburn with Darwen", "Preston", "Atherton (Manchester)"],
  "Crewe": ["Stoke-On-Trent (Cobridge)", "Stoke-on-Trent (Newcastle-Under-Lyme)", "Northwich"],
  "Heysham": ["Kendal (Oxenholme Road)", "Blackpool", "Preston"],
  "Kendal (Oxenholme Road)": ["Heysham", "Barrow In Furness", "Preston"],
  "Macclesfield": ["Buxton", "Bredbury (Manchester)", "West Didsbury (Manchester)"],
  "Nelson": ["Skipton", "Steeton", "Blackburn with Darwen"],
  "Norris Green (Liverpool)": ["Wallasey", "Speke (Liverpool)", "St Helens (Liverpool)"],
  "Northwich": ["Warrington", "Widnes", "Crewe"],
  "Preston": ["Chorley", "Blackburn with Darwen", "Blackpool"],
  "Rochdale (Manchester)": ["Bury (Manchester)", "Chadderton", "Cheetham Hill (Manchester)"],
  "Sale (Manchester)": ["West Didsbury (Manchester)", "Cheetham Hill (Manchester)", "Bredbury (Manchester)"],
  "Skipton": ["Steeton", "Nelson", "Bradford (Heaton)"],
  "Southport (Liverpool)": ["Norris Green (Liverpool)", "Preston", "Chorley"],
  "Speke (Liverpool)": ["Widnes", "Norris Green (Liverpool)", "Wallasey"],
  "St Helens (Liverpool)": ["Warrington", "Widnes", "Norris Green (Liverpool)"],
  "Steeton": ["Skipton", "Bradford (Heaton)", "Nelson"],
  "Upton": ["Wallasey", "Norris Green (Liverpool)", "Speke (Liverpool)"],
  "Wallasey": ["Upton", "Norris Green (Liverpool)", "Speke (Liverpool)"],
  "Warrington": ["St Helens (Liverpool)", "Widnes", "Atherton (Manchester)"],
  "West Didsbury (Manchester)": ["Sale (Manchester)", "Cheetham Hill (Manchester)", "Bredbury (Manchester)"],
  "Widnes": ["Speke (Liverpool)", "St Helens (Liverpool)", "Warrington"],
  "Workington": ["Carlisle", "Carlisle LGV (Cars)", "Kendal (Oxenholme Road)"],

  // ── South-east England ──
  "Ashford (Kent)": ["Canterbury", "Folkestone", "Maidstone"],
  "Aylesbury": ["Leighton Buzzard (Stanbridge Road)", "Bletchley", "High Wycombe"],
  "Banbury": ["Warwick (Wedgenock House)", "Oxford (Cowley)", "Rugby"],
  "Basingstoke": ["Greenham", "Winchester", "Farnborough"],
  "Burgess Hill": ["Crawley", "Worthing", "Redhill Aerodrome"],
  "Canterbury": ["Herne Bay", "Ashford (Kent)", "Folkestone"],
  "Chichester": ["Worthing", "Portsmouth", "Lee On The Solent"],
  "Crawley": ["Burgess Hill", "Redhill Aerodrome", "Worthing"],
  "Eastbourne": ["Hastings (Ore)", "Burgess Hill", "Tunbridge Wells"],
  "Farnborough": ["Guildford", "Chertsey (London)", "Basingstoke"],
  "Folkestone": ["Ashford (Kent)", "Canterbury", "Herne Bay"],
  "Gillingham": ["Maidstone", "Mitcham (London)", "Sevenoaks"],
  "Greenham": ["Reading", "Basingstoke", "Winchester"],
  "Guildford": ["Chertsey (London)", "Farnborough", "Tolworth (London)"],
  "Hastings (Ore)": ["Eastbourne", "Ashford (Kent)", "Tunbridge Wells"],
  "Herne Bay": ["Canterbury", "Ashford (Kent)", "Folkestone"],
  "High Wycombe": ["Slough (London)", "Uxbridge (London)", "Pinner (London)"],
  "Lee On The Solent": ["Portsmouth", "Southampton (Maybush)", "Winchester"],
  "Leighton Buzzard (Stanbridge Road)": ["Bletchley", "Aylesbury", "Luton"],
  "Maidstone": ["Gillingham", "Tunbridge Wells", "Sevenoaks"],
  "Oxford (Cowley)": ["Aylesbury", "Reading", "Banbury"],
  "Portsmouth": ["Lee On The Solent", "Southampton (Maybush)", "Chichester"],
  "Reading": ["Greenham", "Basingstoke", "Farnborough"],
  "Redhill Aerodrome": ["Crawley", "Morden (London)", "West Wickham (London)"],
  "Sevenoaks": ["Mitcham (London)", "Tunbridge Wells", "Sidcup (London)"],
  "Southampton (Maybush)": ["Winchester", "Lee On The Solent", "Portsmouth"],
  "Tunbridge Wells": ["Sevenoaks", "Maidstone", "Mitcham (London)"],
  "Winchester": ["Southampton (Maybush)", "Basingstoke", "Portsmouth"],
  "Worthing": ["Chichester", "Burgess Hill", "Crawley"],

  // ── South-west England ──
  "Barnstaple": ["Launceston", "Exeter", "Taunton"],
  "Bodmin": ["Launceston", "Plymouth", "Camborne"],
  "Bristol (Avonmouth)": ["Bristol (Kingswood)", "Newport (Gwent)", "Weston-super-Mare"],
  "Bristol (Kingswood)": ["Bristol (Avonmouth)", "Chippenham", "Trowbridge"],
  "Camborne": ["Penzance", "Bodmin", "Launceston"],
  "Cheltenham": ["Gloucester", "Worcester", "Swindon"],
  "Chippenham": ["Trowbridge", "Bristol (Kingswood)", "Swindon"],
  "Dorchester": ["Yeovil", "Poole", "Taunton"],
  "Exeter": ["Newton Abbot", "Taunton", "Barnstaple"],
  "Gloucester": ["Cheltenham", "Monmouth", "Bristol (Kingswood)"],
  "Isles of Scilly": ["Penzance", "Camborne", "Bodmin"],
  "Launceston": ["Plymouth", "Bodmin", "Newton Abbot"],
  "Newton Abbot": ["Exeter", "Plymouth", "Launceston"],
  "Penzance": ["Camborne", "Bodmin", "Launceston"],
  "Plymouth": ["Launceston", "Bodmin", "Newton Abbot"],
  "Poole": ["Dorchester", "Salisbury", "Southampton (Maybush)"],
  "Salisbury": ["Southampton (Maybush)", "Winchester", "Trowbridge"],
  "Swindon": ["Chippenham", "Cheltenham", "Trowbridge"],
  "Taunton": ["Yeovil", "Weston-super-Mare", "Exeter"],
  "Trowbridge": ["Chippenham", "Bristol (Kingswood)", "Salisbury"],
  "Weston-super-Mare": ["Bristol (Avonmouth)", "Taunton", "Newport (Gwent)"],
  "Yeovil": ["Dorchester", "Taunton", "Trowbridge"],

  // ── West Midlands ──
  "Birmingham (Garretts Green)": ["Birmingham (South Yardley)", "Birmingham (Shirley)", "Birmingham (Kingstanding)"],
  "Birmingham (Kings Heath)": ["Birmingham (Shirley)", "Birmingham (South Yardley)", "Birmingham (Garretts Green)"],
  "Birmingham (Kingstanding)": ["Wednesbury", "Birmingham (Garretts Green)", "Birmingham (South Yardley)"],
  "Birmingham (Shirley)": ["Birmingham (Kings Heath)", "Birmingham (South Yardley)", "Birmingham (Garretts Green)"],
  "Birmingham (South Yardley)": ["Birmingham (Garretts Green)", "Birmingham (Shirley)", "Birmingham (Kings Heath)"],
  "Burton on Trent": ["Lichfield", "Derby (Alvaston)", "Birmingham (Kingstanding)"],
  "Coventry": ["Nuneaton", "Hinckley", "Warwick (Wedgenock House)"],
  "Dudley": ["Wolverhampton", "Wednesbury", "Featherstone"],
  "Featherstone": ["Wolverhampton", "Wednesbury", "Dudley"],
  "Hereford": ["Monmouth", "Ludlow", "Abergavenny"],
  "Lichfield": ["Birmingham (Kingstanding)", "Burton on Trent", "Wednesbury"],
  "Ludlow": ["Hereford", "Worcester", "Dudley"],
  "Nuneaton": ["Coventry", "Hinckley", "Birmingham (Garretts Green)"],
  "Oswestry": ["Wrexham", "Shrewsbury", "Chester"],
  "Redditch": ["Birmingham (Kings Heath)", "Birmingham (Shirley)", "Birmingham (South Yardley)"],
  "Rugby": ["Hinckley", "Coventry", "Nuneaton"],
  "Shrewsbury": ["Telford", "Oswestry", "Wrexham"],
  "Stafford": ["Featherstone", "Stoke-on-Trent (Newcastle-Under-Lyme)", "Stoke-On-Trent (Cobridge)"],
  "Stoke-On-Trent (Cobridge)": ["Stoke-on-Trent (Newcastle-Under-Lyme)", "Crewe", "Stafford"],
  "Stoke-on-Trent (Newcastle-Under-Lyme)": ["Stoke-On-Trent (Cobridge)", "Crewe", "Stafford"],
  "Telford": ["Shrewsbury", "Featherstone", "Stafford"],
  "Warwick (Wedgenock House)": ["Birmingham (Shirley)", "Coventry", "Birmingham (Kings Heath)"],
  "Wednesbury": ["Wolverhampton", "Birmingham (Kingstanding)", "Dudley"],
  "Wolverhampton": ["Wednesbury", "Dudley", "Featherstone"],
  "Worcester": ["Redditch", "Birmingham (Kings Heath)", "Birmingham (Shirley)"],

  // ── Yorkshire and the Humber ──
  "Barnsley": ["Wakefield", "Rotherham", "Sheffield (Middlewood Road)"],
  "Beverley LGV": ["Hull", "Bridlington", "Scunthorpe"],
  "Bradford (Heaton)": ["Bradford (Thornbury)", "Horsforth", "Halifax"],
  "Bradford (Thornbury)": ["Bradford (Heaton)", "Horsforth", "Heckmondwike"],
  "Bridlington": ["Scarborough", "Beverley LGV", "Hull"],
  "Doncaster": ["Rotherham", "Barnsley", "Worksop"],
  "Halifax": ["Huddersfield", "Bradford (Heaton)", "Heckmondwike"],
  "Heckmondwike": ["Huddersfield", "Wakefield", "Bradford (Thornbury)"],
  "Horsforth": ["Bradford (Thornbury)", "Leeds (Fearnville)", "Bradford (Heaton)"],
  "Huddersfield": ["Heckmondwike", "Halifax", "Wakefield"],
  "Hull": ["Beverley LGV", "Scunthorpe", "Bridlington"],
  "Knaresborough": ["Walton LGV", "Leeds (Fearnville)", "Horsforth"],
  "Leeds (Colton Mill)": ["Leeds (Fearnville)", "Pontefract", "Horsforth"],
  "Leeds (Fearnville)": ["Leeds (Colton Mill)", "Horsforth", "Bradford (Thornbury)"],
  "Malton": ["York", "Scarborough", "Whitby"],
  "Pontefract": ["Leeds (Colton Mill)", "Wakefield", "Leeds (Fearnville)"],
  "Rotherham": ["Sheffield (Handsworth)", "Sheffield (Middlewood Road)", "Barnsley"],
  "Scarborough": ["Bridlington", "Malton", "Whitby"],
  "Scunthorpe": ["Doncaster", "Hull", "Beverley LGV"],
  "Sheffield (Handsworth)": ["Rotherham", "Sheffield (Middlewood Road)", "Worksop"],
  "Sheffield (Middlewood Road)": ["Sheffield (Handsworth)", "Rotherham", "Barnsley"],
  "Wakefield": ["Heckmondwike", "Pontefract", "Huddersfield"],
  "Walton LGV": ["Knaresborough", "Leeds (Fearnville)", "Leeds (Colton Mill)"],
  "Whitby": ["Scarborough", "Malton", "Middlesbrough"],
  "York": ["Walton LGV", "Malton", "Knaresborough"],

  // ── Scotland ──
  "Aberdeen North": ["Aberdeen South (Cove)", "Inverurie", "Peterhead"],
  "Aberdeen South (Cove)": ["Aberdeen North", "Inverurie", "Montrose"],
  "Aberfeldy": ["Pitlochry", "Crieff", "Perth (Arran Road)"],
  "Airdrie": ["Glasgow (Baillieston)", "Hamilton", "Bishopbriggs"],
  "Alness": ["Inverness (Longman Drive)", "Golspie", "Ullapool"],
  "Arbroath": ["Forfar", "Montrose", "Dundee"],
  "Ayr": ["Irvine", "Cumnock", "Girvan"],
  "Ballater": ["Huntly", "Inverurie", "Grantown-On-Spey"],
  "Banff": ["Buckie", "Huntly", "Fraserburgh"],
  "Barra": ["Benbecula Island", "Isle of Tiree", "Mallaig"],
  "Benbecula Island": ["Barra", "Isle of Skye (Portree)", "Mallaig"],
  "Bishopbriggs": ["Glasgow (Anniesland)", "Glasgow (Baillieston)", "Glasgow (Shieldhall)"],
  "Brodick (Isle of Arran)": ["Irvine", "Ayr", "Campbeltown"],
  "Buckie": ["Elgin", "Banff", "Huntly"],
  "Callander": ["Stirling", "Crieff", "Grangemouth"],
  "Campbeltown": ["Brodick (Isle of Arran)", "Irvine", "Ayr"],
  "Castle Douglas": ["Dumfries", "Newton Stewart", "Carlisle LGV (Cars)"],
  "Crieff": ["Perth (Arran Road)", "Stirling", "Aberfeldy"],
  "Cumnock": ["Ayr", "Irvine", "Hamilton"],
  "Dumbarton": ["Glasgow (Anniesland)", "Glasgow (Shieldhall)", "Paisley"],
  "Dumfries": ["Castle Douglas", "Carlisle LGV (Cars)", "Carlisle"],
  "Dundee": ["Forfar", "Arbroath", "Perth (Arran Road)"],
  "Dunfermline (Vine)": ["Kirkcaldy", "Grangemouth", "Edinburgh (Currie)"],
  "Dunoon": ["Greenock", "Rothesay", "Paisley"],
  "Duns": ["Kelso", "Berwick-On-Tweed", "Haddington"],
  "East Kilbride": ["Hamilton", "Glasgow (Baillieston)", "Glasgow (Shieldhall)"],
  "Edinburgh (Currie)": ["Livingston", "Edinburgh (Musselburgh)", "Dunfermline (Vine)"],
  "Edinburgh (Musselburgh)": ["Edinburgh (Currie)", "Haddington", "Livingston"],
  "Elgin": ["Buckie", "Huntly", "Banff"],
  "Forfar": ["Arbroath", "Dundee", "Montrose"],
  "Fort William": ["Mallaig", "Oban", "Kingussie"],
  "Fraserburgh": ["Peterhead", "Banff", "Inverurie"],
  "Gairloch": ["Kyle of Lochalsh", "Ullapool", "Alness"],
  "Galashiels": ["Hawick", "Peebles", "Duns"],
  "Girvan": ["Ayr", "Stranraer", "Newton Stewart"],
  "Glasgow (Anniesland)": ["Glasgow (Shieldhall)", "Bishopbriggs", "Paisley"],
  "Glasgow (Baillieston)": ["Airdrie", "Bishopbriggs", "Hamilton"],
  "Glasgow (Shieldhall)": ["Glasgow (Anniesland)", "Paisley", "Bishopbriggs"],
  "Golspie": ["Alness", "Inverness (Longman Drive)", "Thurso"],
  "Grangemouth": ["Stirling", "Livingston", "Dunfermline (Vine)"],
  "Grantown-On-Spey": ["Kingussie", "Elgin", "Inverness (Longman Drive)"],
  "Greenock": ["Dunoon", "Rothesay", "Paisley"],
  "Haddington": ["Edinburgh (Musselburgh)", "Kelso", "Duns"],
  "Hamilton": ["East Kilbride", "Glasgow (Baillieston)", "Airdrie"],
  "Hawick": ["Galashiels", "Peebles", "Duns"],
  "Huntly": ["Inverurie", "Banff", "Buckie"],
  "Inveraray": ["Lochgilphead", "Oban", "Dunoon"],
  "Inverness (Longman Drive)": ["Alness", "Grantown-On-Spey", "Elgin"],
  "Inverurie": ["Aberdeen North", "Huntly", "Aberdeen South (Cove)"],
  "Irvine": ["Ayr", "Cumnock", "Paisley"],
  "Islay Island": ["Lochgilphead", "Oban", "Brodick (Isle of Arran)"],
  "Isle of Mull": ["Oban", "Fort William", "Inveraray"],
  "Isle of Skye (Portree)": ["Kyle of Lochalsh", "Mallaig", "Benbecula Island"],
  "Isle of Tiree": ["Barra", "Oban", "Isle of Mull"],
  "Kelso": ["Duns", "Haddington", "Berwick-On-Tweed"],
  "Kingussie": ["Grantown-On-Spey", "Inverness (Longman Drive)", "Pitlochry"],
  "Kirkcaldy": ["Dunfermline (Vine)", "Perth (Arran Road)", "Edinburgh (Currie)"],
  "Kyle of Lochalsh": ["Mallaig", "Isle of Skye (Portree)", "Gairloch"],
  "Lanark": ["Hamilton", "Airdrie", "Livingston"],
  "Lerwick": ["Orkney", "Thurso", "Wick"],
  "Livingston": ["Edinburgh (Currie)", "Grangemouth", "Dunfermline (Vine)"],
  "Lochgilphead": ["Inveraray", "Oban", "Rothesay"],
  "Mallaig": ["Kyle of Lochalsh", "Fort William", "Isle of Skye (Portree)"],
  "Montrose": ["Arbroath", "Forfar", "Dundee"],
  "Newton Stewart": ["Stranraer", "Castle Douglas", "Girvan"],
  "Oban": ["Isle of Mull", "Inveraray", "Lochgilphead"],
  "Orkney": ["Thurso", "Wick", "Golspie"],
  "Paisley": ["Glasgow (Shieldhall)", "Glasgow (Anniesland)", "Dumbarton"],
  "Peebles": ["Galashiels", "Edinburgh (Currie)", "Edinburgh (Musselburgh)"],
  "Perth (Arran Road)": ["Crieff", "Dundee", "Pitlochry"],
  "Peterhead": ["Fraserburgh", "Aberdeen North", "Inverurie"],
  "Pitlochry": ["Aberfeldy", "Perth (Arran Road)", "Crieff"],
  "Rothesay": ["Greenock", "Dunoon", "Paisley"],
  "Stirling": ["Grangemouth", "Callander", "Bishopbriggs"],
  "Stornoway": ["Ullapool", "Isle of Skye (Portree)", "Benbecula Island"],
  "Stranraer": ["Newton Stewart", "Girvan", "Ayr"],
  "Thurso": ["Wick", "Orkney", "Golspie"],
  "Ullapool": ["Alness", "Stornoway", "Inverness (Longman Drive)"],
  "Wick": ["Thurso", "Orkney", "Golspie"],

  // ── Wales ──
  "Abergavenny": ["Monmouth", "Newport (Gwent)", "Merthyr Tydfil"],
  "Aberystwyth (Park Avenue)": ["Cardigan", "Newtown", "Carmarthen"],
  "Bala": ["Wrexham", "Oswestry", "Rhyl"],
  "Bangor": ["Rhyl", "Pwllheli", "Bala"],
  "Barry": ["Llantrisant", "Cardiff (Llanishen)", "Bridgend"],
  "Brecon": ["Abergavenny", "Merthyr Tydfil", "Hereford"],
  "Bridgend": ["Llantrisant", "Barry", "Cardiff (Llanishen)"],
  "Cardiff (Llanishen)": ["Llantrisant", "Barry", "Newport (Gwent)"],
  "Cardigan": ["Carmarthen", "Pembroke Dock", "Aberystwyth (Park Avenue)"],
  "Carmarthen": ["Llanelli", "Cardigan", "Swansea"],
  "Llanelli": ["Swansea", "Carmarthen", "Bridgend"],
  "Llantrisant": ["Cardiff (Llanishen)", "Barry", "Bridgend"],
  "Merthyr Tydfil": ["Llantrisant", "Cardiff (Llanishen)", "Abergavenny"],
  "Monmouth": ["Abergavenny", "Hereford", "Newport (Gwent)"],
  "Newport (Gwent)": ["Cardiff (Llanishen)", "Abergavenny", "Llantrisant"],
  "Newtown": ["Oswestry", "Ludlow", "Shrewsbury"],
  "Pembroke Dock": ["Carmarthen", "Cardigan", "Llanelli"],
  "Pwllheli": ["Bangor", "Bala", "Rhyl"],
  "Rhyl": ["Bangor", "Wrexham", "Upton"],
  "Swansea": ["Llanelli", "Bridgend", "Carmarthen"],
  "Wrexham": ["Chester", "Oswestry", "Upton"],
};

// Build the full list of all centre names
export const UK_CENTRES = Object.keys(NEARBY_CENTRES).sort();

// Get all matchable centres for a given centre (itself + its 3 nearby)
export function getMatchableCentres(centre) {
  var nearby = NEARBY_CENTRES[centre] || [];
  return [centre, ...nearby];
}

// Check if two centres can swap with each other (both must be in each other's nearby list)
export function canSwapCentres(centreA, centreB) {
  if (centreA === centreB) return true;
  var aNearby = NEARBY_CENTRES[centreA] || [];
  var bNearby = NEARBY_CENTRES[centreB] || [];
  var aCanMoveToB = aNearby.indexOf(centreB) !== -1;
  var bCanMoveToA = bNearby.indexOf(centreA) !== -1;
  return aCanMoveToB && bCanMoveToA;
}

// Centres a learner can move their test to: their current centre + its nearby
// centres, plus (if they previously swapped) the original centre DVSA lets them
// move back to.
export function reachableCentres(centre, originalCentre) {
  var set = getMatchableCentres(centre);
  if (originalCentre && set.indexOf(originalCentre) === -1) set = set.concat([originalCentre]);
  return set;
}

// A swap is valid only if EACH learner can move to the OTHER's centre — i.e. the
// other's centre is within their reachable set (nearby or their own original).
export function canSwapWithOriginals(aCentre, aOriginal, bCentre, bOriginal) {
  var aReach = reachableCentres(aCentre, aOriginal);
  var bReach = reachableCentres(bCentre, bOriginal);
  return aReach.indexOf(bCentre) !== -1 && bReach.indexOf(aCentre) !== -1;
}
